site_name: Code Doc Skeleton
site_url: https://example.com
repo_url: https://github.com/example/code-doc-skeleton
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy

docs_dir: docs
site_dir: public

nav:
  - Inicio: index.md
  - Flujos de Usuario:
      - Login: flujo-usuarios/login.md
  - Reglas de Negocio:
      - Autenticación: reglas-negocio/autenticacion.md
  - APIs:
      - Login API: apis/login-api.md
  - Cambios:
      - "2025-07-09 Login Social": cambios/2025-07-09-feature-login-social.md
