name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MkDocs and Material theme
        run: pip install mkdocs mkdocs-material

      - name: Verify that index.md exists
        run: test -f docs/index.md

      - name: Build documentation
        run: mkdocs build --strict

      - name: Check if site/ was created
        run: |
          echo "Verificando contenido generado en site/"
          ls -la site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "deploy: auto-update site from main"
